# Generated by Django 6.0.3 on 2026-03-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appliancecategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='appliancecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='appliancecategory',
            name='user',
        ),
    ]
